In [1]:
import numpy as np

In [3]:
l1 = [0,1,2,3,4]
l2 = np.array(l1)
print(l1)
print(type(l1))
print(l2)
print(type(l2))

[0, 1, 2, 3, 4]
<class 'list'>
[0 1 2 3 4]
<class 'numpy.ndarray'>


In [9]:
l2.resize((2,3))
print(l2)
print(l2.shape)

[[0 1 2]
 [3 4 0]]
(2, 3)


In [10]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [11]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [12]:
l2.reshape((3,2))

array([[0, 1],
       [2, 3],
       [4, 0]])

In [13]:
print(l2)

[[0 1 2]
 [3 4 0]]


In [15]:
l2.resize((3,2))
print(l2)

[[0 1]
 [2 3]
 [4 0]]


In [19]:
l4 = np.arange(24).reshape((4,6))
print(l4)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]


In [22]:
l5 = l4[1:3,-3:]
print(l5)

[[ 9 10 11]
 [15 16 17]]
